#https://docker-minecraft-server.readthedocs.io/en/latest/misc/examples/#bedrock-compatible-server
#https://github.com/joesturge/lazymc-docker-proxy
#https://github.com/timvisee/lazymc/blob/master/res/lazymc.toml

networks:
  minecraft-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.32.0/24

services:
  # Router
  router:
    image: itzg/mc-router
    command: "-debug"
    networks:
      minecraft-network:
        ipv4_address: 172.23.32.2
    depends_on:
      - lazymc
    restart: unless-stopped
    environment:
      MAPPING: |
        goopcraft-1.phoboy.org=lazymc:25565
        goopcraft-2.phoboy.org=lazymc:25566
        _dc-srv.88613afad6ef._minecraft._tcp.goopcraft-1.phoboy.org=lazymc:25565
        _dc-srv.88613afad6ef._minecraft._tcp.goopcraft-2.phoboy.org=lazymc:25566
    ports:
      - "${USE_HOST_PORT}:25565"

  # Lazymc Proxy
  lazymc:
    image: ghcr.io/joesturge/lazymc-docker-proxy:latest
    networks:
      minecraft-network:
        ipv4_address: 172.23.32.3
    ports:                                              #Expose ports for direct access to server containers
      - "25565:25565"
      - "25566:25566"
    restart: unless-stopped
    environment:
      RUST_LOG: "trace"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro    #Provide access to docker commands
      - ./goopcraft:/server/server1:ro
      - ./universio:/server/server2:ro

  # Minecraft Instance 1
  mc1:
    image: itzg/minecraft-server:java17
    tty: true
    stdin_open: true
    env_file:
      - .env
    networks:
      minecraft-network:
        ipv4_address: 172.23.32.4
    ports:
      - "${USE_HOST_PORT_VC}:${USE_HOST_PORT_VC}/udp"
    labels:
      - lazymc.enabled=true
      - lazymc.group=mc1
      - lazymc.port=25565                               #Exposed port for lazymc mapping and direct access to server containers
      - lazymc.server.directory=/server/server1
      - lazymc.server.address=mc1:25565
      - lazymc.server.forge=true
      - lazymc.public.version=1.20.1
      - lazymc.public.protocol=763                      #https://minecraft.fandom.com/wiki/Protocol_version
      - lazymc.time.sleep_after=600
      - lazymc.time.minimum_online_time=600
      - lazymc.motd.sleeping="☠ Server is sleeping\n§2☻ Join to start it up (DO NOT REFRESH YOUR SERVERS LIST)"
      - lazymc.motd.starting="§2☻ Server is starting...\n§7⌛ Please wait... (DO NOT REFRESH YOUR SERVERS LIST)"
    restart: no
    environment:
      # General
      MEMORY: "12G" 
      LOG_TIMESTAMP: true
      ENABLE_ROLLING_LOGS: true
      DEBUG: true
      OVERRIDE_SERVER_PROPERTIES: true                  #Uncomment to manually manage server.properties

      # Server
      EULA: "TRUE"
      TYPE: "FORGE"
      VERSION: 1.20.1
      FORGE_VERSION: 47.4.0
      #ICON: "https://cdn.discordapp.com/attachments/675193185743405057/1391533320302755860/ryan.png?ex=686c3de4&is=686aec64&hm=ce2f54df006aa7ccf06266cd3287882d9c50f0ec364a43d05651994b39e44018&"
      MAX_PLAYERS: 8
      ENABLE_COMMAND_BLOCK: "TRUE"
      MAX_BUILD_HEIGHT: 512
      VIEW_DISTANCE: 20
      ALLOW_FLIGHT: "TRUE"
      LEVEL_TYPE: "bclib:normal"
      SPAWN_PROTECTION: 0
      PLAYER_IDLE_TIMEOUT: 10
      SERVER_NAME: goopcraft
      SERVER_PORT: 25565
      RCON_PORT: 25575
      STOP_SERVER_ANNOUNCE_DELAY: 10
      MOTD: "§2☻ Server open! Joining may take multiple attempts (DO NOT REFRESH YOUR SERVERS LIST)"

      # CurseForge (https://docker-minecraft-server.readthedocs.io/en/latest/types-and-platforms/mod-platforms/auto-curseforge/#pinning-modpack-and-mod-loader-versions)
      CF_SERVER_MOD: goopcraft/modpack/goobercraft-server-1.0.0.zip
      CF_API_KEY: "${CF_API_KEY}"
      #CF_SLUG: ""
      #CF_FILE_ID: ""

      # Whitelist
      ENABLE_WHITELIST: true
      WHITELIST: "${WHITELIST}"
      OVERRIDE_WHITELIST: true

      # OPS
      OPS: "${OPS}"
      OVERRIDE_OPS: true
    volumes:
      - ./goopcraft:/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
  
  # Minecraft Instance 2
  mc2:
    image: itzg/minecraft-server:java17
    tty: true
    stdin_open: true
    env_file:
      - .env
    networks:
      minecraft-network:
        ipv4_address: 172.23.32.5
    labels:
      - lazymc.enabled=true
      - lazymc.group=mc2
      - lazymc.port=25566                               #Exposed port for lazymc mapping and direct access to server containers
      - lazymc.server.directory=/server/server2
      - lazymc.server.address=mc2:25565
      - lazymc.server.forge=true
      - lazymc.public.version=1.19.2
      - lazymc.public.protocol=760                      #https://minecraft.fandom.com/wiki/Protocol_version
      - lazymc.time.sleep_after=600
      - lazymc.time.minimum_online_time=600
      - lazymc.motd.sleeping="☠ Server is sleeping\n§2☻ Join to start it up (DO NOT REFRESH YOUR SERVERS LIST)"
      - lazymc.motd.starting="§2☻ Server is starting...\n§7⌛ Please wait... (DO NOT REFRESH YOUR SERVERS LIST)"
    restart: no
    environment:
      # General
      MEMORY: "8G" 
      LOG_TIMESTAMP: true
      ENABLE_ROLLING_LOGS: true
      DEBUG: true
      OVERRIDE_SERVER_PROPERTIES: true                  #Uncomment to manually manage server.properties

      # Server
      EULA: "TRUE"
      TYPE: "FORGE"
      VERSION: 1.19.2
      FORGE_VERSION: 43.2.10
      #ICON: "https://cdn.discordapp.com/attachments/675193185743405057/1391533320302755860/ryan.png?ex=686c3de4&is=686aec64&hm=ce2f54df006aa7ccf06266cd3287882d9c50f0ec364a43d05651994b39e44018&"
      MAX_PLAYERS: 8
      ENABLE_COMMAND_BLOCK: "TRUE"
        #MAX_BUILD_HEIGHT: 512
      VIEW_DISTANCE: 20
      ALLOW_FLIGHT: "TRUE"
      LEVEL_TYPE: "minecraft:normal"
      SPAWN_PROTECTION: 0
      PLAYER_IDLE_TIMEOUT: 10
      SERVER_NAME: universio
      SERVER_PORT: 25565
      RCON_PORT: 25575
      STOP_SERVER_ANNOUNCE_DELAY: 10
      MOTD: "§2☻ Server open! Joining may take multiple attempts (DO NOT REFRESH YOUR SERVERS LIST)"

      # CurseForge (https://docker-minecraft-server.readthedocs.io/en/latest/types-and-platforms/mod-platforms/auto-curseforge/#pinning-modpack-and-mod-loader-versions)
      CF_API_KEY: "${CF_API_KEY}"
      #CF_SLUG: ""
      #CF_FILE_ID: ""

      # Whitelist
      ENABLE_WHITELIST: true
      WHITELIST: "${WHITELIST}"
      OVERRIDE_WHITELIST: true

      # OPS
      OPS: "${OPS}"
      OVERRIDE_OPS: true
    volumes:
      - ./universio:/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
